swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: argent-bank-back-end.vercel.app
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Transactions Module
      summary: User Transactions API
      description: API for retrieving user transactions
      parameters:
        - in: path
          type: string
          name: accountId
          description: get transactions linked to an account
          required: true
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/ResponseTransaction"
        "404":
          description: no transaction found
        "500":
          description: Internal Server Error
  /user/{accountId}/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - User Transactions Module
      summary: User Transactions API
      description: API for retrieving a user transaction
      parameters:
        - in: path
          type: string
          name: accountId
          description: get transaction linked to an account
          required: true
        - in: path
          name: transactionId
          required: true
          type: integer
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: transaction retrieved successfully
          schema:
            $ref: "#/definitions/ResponseTransaction"
        "404":
          description: no transaction found
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Transactions Module
      summary: User Transactions API
      description: API for updating or adding informations to transaction
      parameters:
        - in: path
          type: string
          name: accountId
          description: update transaction linked to an account
          required: true
        - in: path
          name: transactionId
          required: true
          type: integer
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: transaction data to updating
          schema:
            $ref: "#/definitions/Transaction"
      produces:
        - application/json
      responses:
        "201":
          description: transactions updated successfully
          schema:
            $ref: "#/definitions/ResponseTransaction"
        "404":
          description: no transaction found
        "500":
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User Transactions Module
      summary: User Transactions API
      description: API for deleting user transaction
      parameters:
        - in: path
          type: string
          name: accountId
          description: delete transaction linked to an account
          required: true
        - in: path
          name: transactionId
          required: true
          type: integer
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "204":
          description: transaction deleted successfully
        "404":
          description: no transaction found
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string

  Transaction:
    properties:
      category:
        type: string
        description: transaction category
      notes:
        type: string
        description: transaction notes
  ResponseTransaction:
    type: object
    properties:
      description:
        type: string
        description: transaction nature
      amount:
        type: number
        description: transaction amount
      balance:
        type: number
        description: balance amount
      transactionType:
        type: string
        description: transaction type
      category:
        type: string
        description: transaction category
      notes:
        type: string
        description: transaction notes
      createdAt:
        type: string
        description: transaction creation date
